version: '3.3'
services: 
    neo4j:
        container_name: neo4j
        image: neo4j
        restart: always
        environment: 
            - NEO4J_AUTH=neo4j/qweqwe
        volumes: 
            - neo4j:/data 
            - neo4j:/logs
            - neo4j:/var/lib/neo4j/import
            - neo4j:/plugins
        ports: 
            - 7474:7474
            - 7687:7687
        networks:
            - neo4j

networks: 
    neo4j:
        external: true
volumes:
    neo4j:
        external: true