scrape_configs:
- job_name: default
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - trungcs.com:9100
    - 10.199.229.20:9100
