scrape_configs:
- job_name: default
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: a
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.79.22.67:10010
- job_name: b
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.79.22.67:10011
- job_name: c
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.79.22.67:10012
- job_name: d
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.79.22.67:10013
- job_name: e
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.79.22.67:10014
- job_name: promotion
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.30.83.2:38052
