scrape_configs:
- job_name: default
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.199.75.196:2112
    - 10.199.75.196:9100
- job_name: a
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.231.253:10010
- job_name: b
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.231.253:10011
- job_name: c
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.231.253:10012
- job_name: d
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.231.253:10013
