# Use root/example as user/password credentials
version: '3.1'

services:


  postgres:
    image: "postgres"
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=sbs
      - POSTGRES_PASSWORD=CpZrKPUuQZYzVHTchPkQ
      - POSTGRES_DB=ag-slotty
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
     external: true
     
# docker volume create --driver local --opt type=tmpfs --opt device=/data/docker  postgres