# Use root/example as user/password credentials
version: '3.1'

services:


  postgres:
    image: "postgres"
    restart: always
    container_name: "postgres-5432"
    environment:
      - POSTGRES_USER=sbs
      - POSTGRES_PASSWORD=sbs
      - POSTGRES_DB=my_db
    # ports:
    #   - "5432:5432"
    network_mode: "host"
    volumes:
      - ./volumes:/var/lib/postgresql/data

