# Use root/example as user/password credentials
version: '3.1'

services:


  postgres:
    image: "postgres"
    restart: always
    container_name: "postgres-5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    # ports:
    #   - "5432:5432"
    network_mode: "host"
    volumes:
      - post_db:/var/lib/postgresql/data

volumes:
  post_db:
    external: true