# Use root/example as user/password credentials
version: '3.1'

services:
  postgres:
    image: "postgres"
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=${PASS:-123456789}
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - stag

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: trung
      PGADMIN_DEFAULT_PASSWORD: ${UI_PASS:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    networks:
      - stag
    restart: always

volumes:
  pgadmin:
  postgres:
     external: true

networks:
  stag:
   external: true
# docker volume create --driver local --opt type=tmpfs --opt device=/data/volumes/postgres  postgres
