version: "3.3"
#  mkdir -p /data/teamcity/server
#  mkdir -p /data/teamcity/log
#  sudo rm -rf /data/teamcity/server/* && sudo rm -rf /data/teamcity/log/*
#  docker stack deploy --compose-file=teamcity-stack.yml teamcity
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - 8111:8111
    volumes:
      - /data/teamcity/server:/data/teamcity_server/datadir
      - /data/teamcity/log:/opt/teamcity/logs
    networks:
        - stag
  agent:
    image: jetbrains/teamcity-agent
    ports:
      - 9090
    environment:
      - SERVER_URL=${SERVER:-192.168.1.10}:8111
    networks:
        - stag
    
    
  agent_remote:
    image: jetbrains/teamcity-agent
    ports:
    - 9090
    environment:
      - SERVER_URL=${SERVER:-192.168.1.10}:8111
    networks:
        - stag
networks:
  stag:
   external: true
