version: "3.3"
#  mkdir -p /data/teamcity/server
#  mkdir -p /data/temcity/log
#  sudo rm -rf /data/server/* && sudo rm -rf /data/log/*
#  docker stack deploy --compose-file=teamcity-stack.yml teamcity
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - 8111:8111
    volumes:
      - /data/teamcity/server:/data/teamcity_server/datadir
      - /data/teamcity/log:/opt/teamcity/logs
  agent:
    image: jetbrains/teamcity-agent
    ports:
      - 9090
    environment:
      - SERVER_URL=172.31.26.16:8111

  agent_remote:
    image: jetbrains/teamcity-agent
    ports:
    - 9090
    environment:
      - SERVER_URL=vphim.co:8111
networks:
  teamcity:
