version: "3.3"
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - 8111:8111
    volumes:
      - /data/teamcity/server:/data/teamcity_server/datadir
      - /data/teamcity/log:/opt/teamcity/logs
    networks:
      - app
  agent:
    image: jetbrains/teamcity-agent
    ports:
      - 9090
    networks:
        - app
    environment:
      - SERVER_URL=${SERVER:-stag}:8111

networks:
  app:
   external: true