version: "3.8"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://192.168.1.7:9200
    ports:
      - "5601:5601"