version: '3.8'
services:
  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - /data/html:/myhtml
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
#    network_mode: "host"

 
#volumes:
#  html:
#    driver_opts:
#      type: "nfs"
#      o: "addr=vphim.co,nolock,soft,rw"
#      device: ":/mnt/html"
