# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8.0
    #command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    # ports:
    #   - 3306:3306
    network_mode: "host"
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'trung'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: trung
    container_name: "mysql-3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_db:/var/lib/mysql
  
volumes:
  mysql_db:
    external: true
