version: '2'

services:
  spark:
    container_name: spark
    build: 
      context: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes: 
      - /home/trung/spark:/data
      - /home/trung/.ivy2/jars:/opt/bitnami/spark/ivy
    ports:
      - '8080:8080'
      - '8081:8081'
      - '7077:7077'
  spark-worker:
    build: 
      context: .
    ports:
        - '8081'
        - '8082'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
