# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: 'trung'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: trung
    container_name: "my_mysql"
    volumes:
      - /data/docker/mysql:/var/lib/mysql

  postgres:
    image: "postgres"
    restart: always
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - /data/docker/postgres:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    container_name: "my_redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

