version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    build: .
    restart: always
    ports:
      - "9092"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: trungtvq.ddns.net
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
