version: '3.2'
services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
    # ports:
    #   - 8083:8083
    #   - 8086:8086
networks:
  default:
    external:
      name: backend