version: '3.1'

services:

  mongodb:
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/bitnami:rw
    environment:
      - MONGODB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongodb:
    external: true
