version: '2'
services:
    
    mongodb:
        image: mongo:latest
        restart: always
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="trung" 
          - MONGODB_PASS="pass@123"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
    #    command: mongod --smallfiles --logpath=/dev/null # --quiet
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #       - 8081:8081
    #     environment:
    #       ME_CONFIG_MONGODB_ADMINUSERNAME: trung
    #       ME_CONFIG_MONGODB_ADMINPASSWORD: pass@123